import Head from 'next/head'


export default function Home() {
  return (
    <div className="flex items-center bg-gray-700 h-screen justify-center">
      <Head>
        <title>Tazama Afrik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-green-500 text-4xl">Tazama Afrik Application</h1>
    </div>
  )
}
